name: ncatest.cx.js
on:
  push:
    branches:
      - main
  schedule:   
    - cron: '35 7 * * 4'   #国际标准时间，北京时间+8
    - cron: '0 9 * * 5'   #国际标准时间，北京时间+8
 
jobs:
  run-csjs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main  #采用main分支下的
           
      - name: Setup Node.js
        uses: actions/setup-node@v3  #安装node.js
        with:
          node-version: '19.x'
          
      - name: Install Dependency       
        run: |
          npm install
          npm install request
      - name: run script
        if: github.event.schedule == '35 7 * * 4'
        run: node ./Tata.js  
      - name: run script
        if: github.event.schedule == '0 9 * * 5'
        run: node ./Friday.js  
 

